language: python
python:
  - "3.8"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - cp contrib/env-sample .env
  - unset DATABASE_URL
  - export DATABASE_URL=postgres://postgres@localhost/travisci
  - pip install pip -U
  - pip install -r requirements.txt
  - python manage.py migrate --noinput

stages:
  - name: check
  - name: tests

jobs:
  include:
    - stage: check
      name: checking application integrity
      script: python manage.py check
    - stage: tests
      name: testing the application
      script: python manage.py test
