# Generated by Django 3.0.8 on 2020-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.GenericIPAddressField(help_text='Agent ip address.', unique=True, verbose_name='ip address'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='environment',
            field=models.CharField(choices=[('PRODUCTION', 'PRODUCTION'), ('HOMOLOGATION', 'HOMOLOGATION'), ('DEVELOPMENT', 'DEVELOPMENT')], help_text='Agent environment type.', max_length=15, verbose_name='environment'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(help_text='Agent name.', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.BooleanField(default=True, help_text='Agent status.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='version',
            field=models.CharField(help_text='Agent version.', max_length=5, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('DEBUG', 'DEBUG'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO')], help_text='Event level.', max_length=20, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='event',
            name='message',
            field=models.TextField(help_text='Message pertinent to the event.', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='event',
            name='occurrences',
            field=models.IntegerField(editable=False, help_text='Number of event occurrences.', verbose_name='occurrences'),
        ),
        migrations.AlterField(
            model_name='event',
            name='received_in',
            field=models.DateField(auto_now_add=True, help_text='Date of received of the event.', verbose_name='received in'),
        ),
        migrations.AlterField(
            model_name='event',
            name='shelved',
            field=models.BooleanField(default=False, help_text='Event has been shelved.', verbose_name='shelved'),
        ),
    ]
