# Generated by Django 3.0.8 on 2020-07-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200715_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='occurrences',
            field=models.IntegerField(blank=True, editable=False, help_text='Number of event occurrences.', verbose_name='occurrences'),
        ),
    ]
