# Generated by Django 3.0.8 on 2020-07-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200715_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-received_in',)},
        ),
    ]
